#!/usr/bin/env python3

import json
from pathlib import Path

from jsonc import load_jsonc


ROOT = Path(__file__).resolve().parent
CONFIG_PATH = ROOT / "block.config.json"
HEADER_PATH = ROOT / "block.config.hpp"


def load_config() -> dict:
	return load_jsonc(CONFIG_PATH)


def constexpr_name(key: str) -> str:
	return key.lower()


def constexpr_decl(key: str, value: object) -> str:
	name = constexpr_name(key)
	if isinstance(value, bool):
		value_str = "true" if value else "false"
		return f"inline constexpr bool {name} = {value_str};"
	if isinstance(value, int):
		return f"inline constexpr usize {name} = {value};"
	if isinstance(value, float):
		return f"inline constexpr f64 {name} = {repr(value)};"
	if isinstance(value, str):
		return f"inline constexpr char {name}[] = {json.dumps(value)};"
	raise TypeError(f"Unsupported config value type: {type(value).__name__}")


def render_header(config: dict) -> str:
	lines = [
		"#pragma once",
		"",
		"// Generated by block_cpp_config.py from block.config.json.",
		"",
		"#include \"cuda/utils.cuh\"",
		"",
		"namespace config {",
	]
	for key, value in config.items():
		lines.append(f"\t{constexpr_decl(key, value)}")
	lines.append("}")
	lines.append("")
	return "\n".join(lines)


def main() -> None:
	config = load_config()
	HEADER_PATH.write_text(render_header(config), encoding="ascii")
	print(f"Created {HEADER_PATH}")


if __name__ == "__main__":
	main()
