#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage:"
  echp "	$0 <binary_file>"
  exit 1
fi

BIN="$1"

set -x
ncu --metrics sm__inst_executed_pipe_tensor_op_hmma,sm__inst_executed_op_ldsm,l1tex__data_pipe_lsu_wavefronts_mem_shared,l1tex__data_bank_conflicts_pipe_lsu_mem_shared_op_ld,l1tex__data_bank_conflicts_pipe_lsu_mem_shared_op_st,smsp__warp_issue_stalled_barrier_per_warp_active,smsp__warp_issue_stalled_branch_resolving_per_warp_active,smsp__warp_issue_stalled_dispatch_stall_per_warp_active,smsp__warp_issue_stalled_drain_per_warp_active,smsp__warp_issue_stalled_imc_miss_per_warp_active,smsp__warp_issue_stalled_lg_throttle_per_warp_active,smsp__warp_issue_stalled_long_scoreboard_per_warp_active,smsp__warp_issue_stalled_long_scoreboard_pipe_l1tex_per_warp_active,smsp__warp_issue_stalled_math_pipe_throttle_per_warp_active,smsp__warp_issue_stalled_membar_per_warp_active,smsp__warp_issue_stalled_mio_throttle_per_warp_active,smsp__warp_issue_stalled_mio_throttle_pipe_mio_per_warp_active,smsp__warp_issue_stalled_misc_per_warp_active,smsp__warp_issue_stalled_no_instruction_per_warp_active,smsp__warp_issue_stalled_not_selected_per_warp_active,smsp__warp_issue_stalled_selected_per_warp_active,smsp__warp_issue_stalled_short_scoreboard_per_warp_active,smsp__warp_issue_stalled_sleeping_per_warp_active,smsp__warp_issue_stalled_tex_throttle_per_warp_active,smsp__warp_issue_stalled_wait_per_warp_active,sm__cycles_active \
	--launch-count 1 \
	--target-processes all "${BIN}"
