//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_attn_kernel.
//
//------------------------------------------------------------------------------

#include "../../../cuda/attn_fwd_i8.cuh"

namespace {
	static constexpr usize N_HEADS = {{n_heads}};
	static constexpr usize HEADS_PER_KERNEL = {{heads_per_kernel}};
	static constexpr usize HEAD_DIM = {{head_dim}};
	static constexpr usize Q_STRIDE = {{q_stride}};
	static constexpr usize KV_STRIDE = {{kv_stride}};
	static constexpr usize O_STRIDE = {{o_stride}};

	using Kernel = AttnForward<
		N_HEADS,
		HEADS_PER_KERNEL,
		HEAD_DIM,
		Q_STRIDE,
		KV_STRIDE,
		O_STRIDE
	>;
}
