//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_attn_kernel.
//
//------------------------------------------------------------------------------

#include "common.cuh"

extern "C" X17_KERNEL(Kernel::THREADS_PER_BLOCK)
void kernel(
	usize seq_len,
	FixedI8 *q,
	FixedI8 *kv,
	FixedI8 const *sink_k,
	FixedI8 const *sink_v,
	f32 const *attn_temperature,
	i32 const *maxes,
	FixedI8 *out,
	f32 *l,
	usize window_size
) {
	Kernel attn_forward;
	attn_forward.run(
		seq_len,
		q,
		kv,
		sink_k,
		sink_v,
		attn_temperature,
		maxes,
		out,
		l,
		window_size
	);
}
