//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_attn_kernel.
//
//------------------------------------------------------------------------------

#include "common.cuh"
#include <cstdio>

int main() {
	printf("{\n");
	printf("\t\"THREADS_PER_BLOCK\": %zu,\n", usize(Kernel::THREADS_PER_BLOCK));
	printf("\t\"SMEM_BYTES\": %zu,\n", usize(Kernel::SMEM_BYTES));
	printf("\t\"Q_PER_BLOCK\": %zu\n", usize(Kernel::Q_PER_BLOCK));
	printf("}\n");
}
