//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "../../cuda/utils.cuh"
#include "../../cuda/gemm_b8.cuh"

namespace {{namespace_name}} {
	static constexpr usize A_COLS = {{a_cols}};
	static constexpr usize B_COLS = A_COLS;

	using InputLoader =
		b8::MatrixLoader<
			b8::FixedI8,
			A_COLS,
			64, 128
		>;

	using WeightLoader =
		b8::MatrixTransLoader<
			b8::MatrixLoader<
				b8::FixedI8,
				B_COLS,
				128, 128
			>
		>;

	using Writer = b8::FixedI8MatrixWriter<
		InputLoader::M,
		WeightLoader::K,
		{{scale_val}} // {{scale_dscr}}
	>;

	using Kernel = b8::Gemm<InputLoader, WeightLoader, Writer>;

	X17_KERNEL(Kernel::THREADS_PER_BLOCK)
	void kernel(
		b8::FixedI8 *a, usize a_rows,
		b8::FixedI8 *b, usize b_rows,
		b8::FixedI8 *c
	) {
		{% match b_rows -%}
		{% when Some with (rows) %}
		b_rows = {{rows}};
		{% when None -%}
		{% endmatch %}

		auto a_loader = InputLoader(a, a_rows);
		auto b_loader = WeightLoader(b, b_rows);
		auto c_writer = Writer(c, b_rows);
		Kernel().run(a_loader, b_loader, c_writer);
	}
}

using namespace {{namespace_name}};

extern "C" {
	usize {{init_name}}() {
		cudaError_t err = cudaFuncSetAttribute(
			kernel,
			cudaFuncAttributeMaxDynamicSharedMemorySize,
			Kernel::SMEM_BYTES
		);
		if (err != cudaSuccess) {
			return int(err);
		}

		err = cudaFuncSetAttribute(
			kernel,
			cudaFuncAttributePreferredSharedMemoryCarveout,
			100
		);

		static_assert(cudaSuccess == 0);
		return usize(err);
	}

	usize {{destroy_name}}() {
		return 0;
	}

	usize {{launcher_name}}(
		b8::FixedI8 *a, usize a_rows,
		b8::FixedI8 *b, usize b_rows,
		b8::FixedI8 *c
	) {
		dim3 grid = Kernel::output_grid(a_rows, b_rows);
		kernel<<<grid, Kernel::THREADS_PER_BLOCK, Kernel::SMEM_BYTES>>>(
			a, a_rows,
			b, b_rows,
			c
		);

		// TODO: is calling cudaGetLastError() efficient?
		// Could I get the error code some other way?
		cudaError_t err = cudaGetLastError();

		static_assert(cudaSuccess == 0);
		return usize(err);
	}
}
