//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "../../cuda/utils.cuh"
#include "../../cuda/gemm_b8.cuh"

#include <cuda.h>
#include <cuda_runtime.h>
#include <nvrtc.h>

namespace {
	usize check_no_context() {
		#ifndef NDEBUG
		CUcontext current_ctx = nullptr;
		CUresult err = cuCtxGetCurrent(&current_ctx);
		if (err != CUDA_SUCCESS) {
			return usize(err);
		}
		if (current_ctx != nullptr) {
			return usize(CUDA_ERROR_INVALID_CONTEXT);
		}
		#endif
		return 0;
	}

	static constexpr usize A_COLS = {{a_cols}};
	static constexpr usize B_COLS = A_COLS;

	using InputLoader =
		b8::MatrixLoader<
			b8::FixedI8,
			A_COLS,
			64, 128
		>;

	using WeightLoader =
		b8::MatrixTransLoader<
			b8::MatrixLoader<
				b8::FixedI8,
				B_COLS,
				128, 128
			>
		>;

	using Writer = b8::FixedI8MatrixWriter<
		InputLoader::M,
		WeightLoader::K,
		{{scale_val}} // {{scale_dscr}}
	>;

	using Kernel = b8::Gemm<InputLoader, WeightLoader, Writer>;

	X17_KERNEL(Kernel::THREADS_PER_BLOCK)
	void kernel(
		b8::FixedI8 *a, usize a_rows,
		b8::FixedI8 *b, usize b_rows,
		b8::FixedI8 *c
	) {
		{% match b_rows -%}
		{% when Some with (rows) %}
		b_rows = {{rows}};
		{% when None -%}
		{% endmatch %}

		auto a_loader = InputLoader(a, a_rows);
		auto b_loader = WeightLoader(b, b_rows);
		auto c_writer = Writer(c, b_rows);
		Kernel().run(a_loader, b_loader, c_writer);
	}
}

extern "C" {
	usize x17ai_kernel_init(CUcontext cuda_context) {
		if (cuda_context == nullptr) {
			return usize(CUDA_ERROR_INVALID_CONTEXT);
		}

		usize result = check_no_context();
		if (result != 0) {
			return result;
		}

		CUresult ctx_err = cuCtxPushCurrent(cuda_context);
		if (ctx_err != CUDA_SUCCESS) {
			return usize(ctx_err);
		}

		cudaError_t err = cudaFuncSetAttribute(
			kernel,
			cudaFuncAttributeMaxDynamicSharedMemorySize,
			Kernel::SMEM_BYTES
		);
		if (err != cudaSuccess) {
			result = usize(err);
		}

		if (result == 0) {
			err = cudaFuncSetAttribute(
				kernel,
				cudaFuncAttributePreferredSharedMemoryCarveout,
				100
			);
			result = usize(err);
		}

		CUcontext popped_ctx = nullptr;
		ctx_err = cuCtxPopCurrent(&popped_ctx);
		if (result == 0 && ctx_err != CUDA_SUCCESS) {
			result = usize(ctx_err);
		}
		if (result == 0 && popped_ctx != cuda_context) {
			result = usize(CUDA_ERROR_INVALID_CONTEXT);
		}
		if (result == 0) {
			result = check_no_context();
		}

		static_assert(cudaSuccess == 0);
		static_assert(CUDA_SUCCESS == 0);
		return result;
	}

	usize x17ai_kernel_deinit() {
		return 0;
	}

	struct CudaStreamHandle;

	usize x17ai_kernel_launch(
		CudaStreamHandle *cuda_stream,
		b8::FixedI8 *a, usize a_rows,
		b8::FixedI8 *b, usize b_rows,
		b8::FixedI8 *c
	) {
		usize result = check_no_context();
		if (result != 0) {
			return 5000 + result;
		}

		dim3 grid = Kernel::output_grid(a_rows, b_rows);
		kernel<<<grid, Kernel::THREADS_PER_BLOCK, Kernel::SMEM_BYTES, reinterpret_cast<cudaStream_t>(cuda_stream)>>>(
			a, a_rows,
			b, b_rows,
			c
		);

		// TODO: is calling cudaGetLastError() efficient?
		// Could I get the error code some other way?
		result = check_no_context();
		if (result != 0) {
			return 8000 + result;
		}

		result = cudaGetLastError();

		static_assert(cudaSuccess == 0);
		return result;
	}
}
