//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "block.config.hpp"
#include "utils2.cuh"
#include "cuda/utils_b8.cuh"
#include "cuda/gemm_b8.cuh"

namespace {{namespace_name}} {
	static constexpr usize A_COLS = {{a_cols}};
	static constexpr usize C_COLS = {{c_cols}};

	using InputLoader =
		b8::MatrixLoader<
			b8::FixedI8,
			A_COLS,
			64, 128
		>;

	using WeightLoader =
		b8::MatrixTransLoader<
			b8::MatrixLoader<
				b8::FixedI8,
				A_COLS,
				128, 128
			>
		>;

	using Writer = b8::FixedI8MatrixWriter<
		C_COLS,
		InputLoader::M,
		WeightLoader::K,
		{{scale}}
	>;

	using Kernel = b8::Gemm<InputLoader, WeightLoader, Writer>;

	X17_KERNEL(Kernel::THREADS_PER_BLOCK)
	void kernel(
		b8::FixedI8 *a,
		b8::FixedI8 *b,
		usize a_rows,
		b8::FixedI8 *c
	) {
		auto a_loader = InputLoader(a, a_rows);
		auto b_loader = WeightLoader(b, C_COLS);
		auto c_writer = Writer(c);
		Kernel().run(a_loader, b_loader, c_writer);
	}
}

extern "C" int {{launcher_name}}(
	b8::FixedI8 *a,
	b8::FixedI8 *b,
	usize a_rows,
	b8::FixedI8 *c
) {
	using namespace {{namespace_name}};

	cudaError_t err = cudaFuncSetAttribute(
		kernel,
		cudaFuncAttributeMaxDynamicSharedMemorySize,
		Kernel::SMEM_BYTES
	);
	if (err != cudaSuccess) {
		return int(err);
	}

	err = cudaFuncSetAttribute(
		kernel,
		cudaFuncAttributePreferredSharedMemoryCarveout,
		100
	);
	if (err != cudaSuccess) {
		return int(err);
	}

	dim3 grid = Kernel::output_grid(a_rows, C_COLS);
	kernel<<<grid, Kernel::THREADS_PER_BLOCK, Kernel::SMEM_BYTES>>>(
		a,
		b,
		a_rows,
		c
	);

	err = cudaGetLastError();
	if (err != cudaSuccess) {
		return int(err);
	}

	return 0;
}
