//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "../../../cuda/utils.cuh"
#include "../../../cuda/gemm_b8.cuh"

namespace {
	static constexpr usize A_COLS = {{a_cols}};
	static constexpr usize B_COLS = A_COLS;

	using InputLoader =
		b8::MatrixLoader<
			b8::FixedI8,
			A_COLS,
			64, 128
		>;

	using WeightLoader =
		b8::MatrixTransLoader<
			b8::MatrixLoader<
				b8::FixedI8,
				B_COLS,
				128, 128
			>
		>;

	{% if writer.use_l2_norm %}
	using Writer = b8::L2NormMatrixWriter<
		{{writer.head_dim}}, // HEAD_DIM
		{{writer.sep_dim}}, // SEP_DIM
		{{writer.eps_val}}, // EPS
		{{writer.head_scale_val}}, // HEAD_SCALE = {{writer.head_scale_dscr}}
		{{writer.sep_scale_val}}, // SEP_SCALE = {{writer.sep_scale_dscr}}
		InputLoader::M, // M_PER_BLOCK
		WeightLoader::K // N_PER_BLOCK
	>;
	{% else %}
	using Writer = b8::FixedI8MatrixWriter<
		InputLoader::M, // M_PER_BLOCK
		WeightLoader::K, // N_PER_BLOCK
		{{writer.scale_val}} // SCALE = {{writer.scale_dscr}}
	>;
	{% endif %}

	using Kernel = b8::Gemm<InputLoader, WeightLoader, Writer>;
}
