//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "../../../cuda/utils.cuh"
#include "../../../cuda/gemm_b8.cuh"
#include "../../../cuda/gemm_b16.cuh"

namespace {
	static constexpr usize A_COLS = {{a_cols}};
	static constexpr usize B_COLS = A_COLS;
	{% if use_b16_gemm %}
	namespace gemm_namespace = b16;
	static constexpr usize K_STEP = 64;
	{% else %}
	namespace gemm_namespace = b8;
	static constexpr usize K_STEP = 128;
	{% endif %}

	using InputLoader =
		gemm_namespace::{{a_loader}}<
			A_COLS,
			64, K_STEP
		>;

	using WeightLoader =
		gemm_namespace::MatrixTransLoader<
			gemm_namespace::{{b_loader}}<
				B_COLS,
				128, K_STEP
			>
		>;

	{% if writer.use_l2_norm %}
	using Writer = b8::L2NormMatrixWriter<
		{{writer.store_type}},
		{{writer.head_dim}}, // HEAD_DIM
		{{writer.sep_dim}}, // SEP_DIM
		{{writer.eps_val}}, // EPS
		{{writer.head_scale_val}}, // HEAD_SCALE = {{writer.head_scale_dscr}}
		{{writer.sep_scale_val}}, // SEP_SCALE = {{writer.sep_scale_dscr}}
		InputLoader::M, // M_PER_BLOCK
		WeightLoader::K // N_PER_BLOCK
	>;
	{% else %}
	{% if writer.use_geglu %}
	using Writer = b8::GeGluMatrixWriter<
		{{writer.store_type}},
		InputLoader::M, // M_PER_BLOCK
		WeightLoader::K, // N_PER_BLOCK
		{{writer.geglu_inp_scale_val}}, // INP_SCALE = {{writer.geglu_inp_scale_dscr}}
		{{writer.geglu_out_scale_val}} // OUT_SCALE = {{writer.geglu_out_scale_dscr}}
	>;
	{% else %}
	{% if writer.use_residual %}
	using Writer = b8::ResidualMatrixWriter<
		{{writer.store_type}},
		InputLoader::M, // M_PER_BLOCK
		WeightLoader::K, // N_PER_BLOCK
		{{writer.scale_val}} // SCALE = {{writer.scale_dscr}}
	>;
	{% else %}
	using Writer = b8::ScaledMatrixWriter<
		{{writer.store_type}},
		InputLoader::M, // M_PER_BLOCK
		WeightLoader::K, // N_PER_BLOCK
		{{writer.scale_val}} // SCALE = {{writer.scale_dscr}}
	>;
	{% endif %}
	{% endif %}
	{% endif %}

	using Kernel = gemm_namespace::Gemm<InputLoader, WeightLoader, Writer>;
}
