//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "common.cuh"

extern "C" X17_KERNEL(Kernel::THREADS_PER_BLOCK)
void kernel(
	{{a_cpp_type}} *a, usize a_rows,
	{{b_cpp_type}} *b, usize b_rows,
	{{writer.c_type}} *c{% if writer.has_rrms_output %},
	f32 *rrms{% endif %}{% if writer.has_residual_input %},
	b8::FixedI8 *residual{% endif %}
) {
	{% match b_rows -%}
	{% when Some with (rows) %}
	// override b_rows with the known value so the compiler can do constant folding
	b_rows = {{rows}};
	{% when None -%}
	{% endmatch %}

	auto a_loader = InputLoader(a, a_rows);
	auto b_loader = WeightLoader(b, b_rows);
	{% if writer.has_residual_input %}
	auto c_writer = Writer(c, residual, {{writer.c_stride_expr}});
	{% else %}
	auto c_writer = Writer(c, {{writer.c_stride_expr}}{% if writer.has_rrms_output %}, rrms{% endif %});
	{% endif %}
	Kernel().run(a_loader, b_loader, c_writer);
}
