//------------------------------------------------------------------------------
//
// Generated by x17ai::device::cuda::generate_gemm_kernel.
//
//------------------------------------------------------------------------------

#include "common.cuh"
#include <cstdio>

int main() {
	printf("{\n");
	printf("\t\"A_COLS\": %zu,\n", usize({{a_cols}}));

	{% match b_rows -%}
	{% when Some with (rows) %}
	printf("\t\"B_ROWS\": %zu,\n", usize({{rows}}));
	{% when None -%}
	{% endmatch %}

	printf("\t\"THREADS_PER_BLOCK\": %zu,\n", usize(Kernel::THREADS_PER_BLOCK));
	printf("\t\"SMEM_BYTES\": %zu,\n", usize(Kernel::SMEM_BYTES));
	printf("\t\"M_PER_BLOCK\": %zu,\n", usize(Kernel::M_PER_BLOCK));
	printf("\t\"N_PER_BLOCK\": %zu\n", usize(Kernel::N_PER_BLOCK));
	printf("}\n");
}
